/*
 * generated by Xtext 2.40.0
 */
package no.ntnu.tdt4250.rf.ui.tests;

import com.google.inject.Injector;
import no.ntnu.tdt4250.rfdsl.ui.internal.RfdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RealmForgeDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RfdslActivator.getInstance().getInjector("no.ntnu.tdt4250.rf.RealmForgeDsl");
	}

}
