# Labels
gameView.label.name=null
gameView.label.health=null
gameView.label.mana=null
gameView.label.gold=null
gameView.label.score=null
gameView.label.inventory=null
gameView.label.passageTitle=null
gameView.label.choices=null

# Buttons
gameView.button.goal=null
gameView.button.menu=null
gameView.button.resume=null
gameView.button.save=null
gameView.button.load=null
gameView.button.settings=null
gameView.button.exitToMenu=null
gameView.button.exitToDesktop=null
