/*
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.rf;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RealmForgeDslStandaloneSetup extends RealmForgeDslStandaloneSetupGenerated {

	public static void doSetup() {
		new RealmForgeDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
