/*
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.rf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RealmForgeDslUiModule extends AbstractRealmForgeDslUiModule {

	public RealmForgeDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
