/**
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.rf.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import no.ntnu.tdt4250.rf.Event;
import no.ntnu.tdt4250.rf.EventPack;
import no.ntnu.tdt4250.rf.EventResult;
import no.ntnu.tdt4250.rf.TypeRacerEvent;
import no.ntnu.tdt4250.rf.services.RealmForgeDslGrammarAccess;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;

@SuppressWarnings("all")
public class RealmForgeDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private RealmForgeDslGrammarAccess _realmForgeDslGrammarAccess;

  protected void _format(final EventPack eventPack, @Extension final IFormattableDocument document) {
    EList<Event> _events = eventPack.getEvents();
    for (final Event event : _events) {
      document.<Event>format(event);
    }
  }

  protected void _format(final TypeRacerEvent typeRacerEvent, @Extension final IFormattableDocument document) {
    document.<EventResult>format(typeRacerEvent.getResult());
  }

  @XbaseGenerated
  public void format(final Object typeRacerEvent, final IFormattableDocument document) {
    if (typeRacerEvent instanceof XtextResource) {
      _format((XtextResource)typeRacerEvent, document);
      return;
    } else if (typeRacerEvent instanceof TypeRacerEvent) {
      _format((TypeRacerEvent)typeRacerEvent, document);
      return;
    } else if (typeRacerEvent instanceof EventPack) {
      _format((EventPack)typeRacerEvent, document);
      return;
    } else if (typeRacerEvent instanceof EObject) {
      _format((EObject)typeRacerEvent, document);
      return;
    } else if (typeRacerEvent == null) {
      _format((Void)null, document);
      return;
    } else if (typeRacerEvent != null) {
      _format(typeRacerEvent, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(typeRacerEvent, document).toString());
    }
  }
}
