/*
 * generated by Xtext 2.40.0
 */
package no.ntnu.tdt4250.rf.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RealmForgeDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class EventPackElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.rf.RealmForgeDsl.EventPack");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cDescriptionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDescriptionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionEStringParserRuleCall_3_0 = (RuleCall)cDescriptionAssignment_3.eContents().get(0);
		private final Keyword cUnitKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cUnitAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cUnitEStringParserRuleCall_5_0 = (RuleCall)cUnitAssignment_5.eContents().get(0);
		private final Assignment cEventsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cEventsEventParserRuleCall_6_0 = (RuleCall)cEventsAssignment_6.eContents().get(0);
		
		//EventPack returns EventPack:
		//    'name' name=EString
		//    'description' description=EString
		//    'unit' unit=EString
		//    (events+=Event)*
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//'name' name=EString
		//'description' description=EString
		//'unit' unit=EString
		//(events+=Event)*
		public Group getGroup() { return cGroup; }
		
		//'name'
		public Keyword getNameKeyword_0() { return cNameKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'description'
		public Keyword getDescriptionKeyword_2() { return cDescriptionKeyword_2; }
		
		//description=EString
		public Assignment getDescriptionAssignment_3() { return cDescriptionAssignment_3; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_3_0() { return cDescriptionEStringParserRuleCall_3_0; }
		
		//'unit'
		public Keyword getUnitKeyword_4() { return cUnitKeyword_4; }
		
		//unit=EString
		public Assignment getUnitAssignment_5() { return cUnitAssignment_5; }
		
		//EString
		public RuleCall getUnitEStringParserRuleCall_5_0() { return cUnitEStringParserRuleCall_5_0; }
		
		//(events+=Event)*
		public Assignment getEventsAssignment_6() { return cEventsAssignment_6; }
		
		//Event
		public RuleCall getEventsEventParserRuleCall_6_0() { return cEventsEventParserRuleCall_6_0; }
	}
	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.rf.RealmForgeDsl.Event");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTypeRacerEventParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cQuestionEventParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Event returns Event:
		//    TypeRacerEvent | QuestionEvent;
		@Override public ParserRule getRule() { return rule; }
		
		//TypeRacerEvent | QuestionEvent
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TypeRacerEvent
		public RuleCall getTypeRacerEventParserRuleCall_0() { return cTypeRacerEventParserRuleCall_0; }
		
		//QuestionEvent
		public RuleCall getQuestionEventParserRuleCall_1() { return cQuestionEventParserRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.rf.RealmForgeDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.rf.RealmForgeDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class EDoubleObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.rf.RealmForgeDsl.EDoubleObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDoubleObject returns ecore::EDoubleObject:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.rf.RealmForgeDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EventResultElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.rf.RealmForgeDsl.EventResult");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEventResultAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cMessageKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cMessageAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cMessageEStringParserRuleCall_2_1_0 = (RuleCall)cMessageAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//EventResult returns EventResult:
		//    {EventResult}
		//    '{'
		//        ('message' message=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{EventResult}
		//'{'
		//    ('message' message=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{EventResult}
		public Action getEventResultAction_0() { return cEventResultAction_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('message' message=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'message'
		public Keyword getMessageKeyword_2_0() { return cMessageKeyword_2_0; }
		
		//message=EString
		public Assignment getMessageAssignment_2_1() { return cMessageAssignment_2_1; }
		
		//EString
		public RuleCall getMessageEStringParserRuleCall_2_1_0() { return cMessageEStringParserRuleCall_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class TypeRacerEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.rf.RealmForgeDsl.TypeRacerEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTypeRacerEventKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIsCaseSensitiveAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cIsCaseSensitiveIsCaseSensitiveKeyword_2_0 = (Keyword)cIsCaseSensitiveAssignment_2.eContents().get(0);
		private final Keyword cDifficultyKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDifficultyAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDifficultyDifficultyEnumRuleCall_4_0 = (RuleCall)cDifficultyAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTimeLimitKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTimeLimitAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTimeLimitEDoubleObjectParserRuleCall_5_1_0 = (RuleCall)cTimeLimitAssignment_5_1.eContents().get(0);
		private final Keyword cRetriesKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cRetriesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cRetriesEIntParserRuleCall_7_0 = (RuleCall)cRetriesAssignment_7.eContents().get(0);
		private final Keyword cSentenceKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cSentenceAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cSentenceEStringParserRuleCall_9_0 = (RuleCall)cSentenceAssignment_9.eContents().get(0);
		private final Keyword cResultKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cResultAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cResultEventResultParserRuleCall_11_0 = (RuleCall)cResultAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//TypeRacerEvent returns TypeRacerEvent:
		//    'TypeRacerEvent'
		//    '{'
		//        (isCaseSensitive?='isCaseSensitive')?
		//        'difficulty' difficulty=Difficulty
		//        ('timeLimit' timeLimit=EDoubleObject)?
		//        'retries' retries=EInt
		//        'sentence' sentence=EString
		//        'result' result=EventResult
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'TypeRacerEvent'
		//'{'
		//    (isCaseSensitive?='isCaseSensitive')?
		//    'difficulty' difficulty=Difficulty
		//    ('timeLimit' timeLimit=EDoubleObject)?
		//    'retries' retries=EInt
		//    'sentence' sentence=EString
		//    'result' result=EventResult
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'TypeRacerEvent'
		public Keyword getTypeRacerEventKeyword_0() { return cTypeRacerEventKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//(isCaseSensitive?='isCaseSensitive')?
		public Assignment getIsCaseSensitiveAssignment_2() { return cIsCaseSensitiveAssignment_2; }
		
		//'isCaseSensitive'
		public Keyword getIsCaseSensitiveIsCaseSensitiveKeyword_2_0() { return cIsCaseSensitiveIsCaseSensitiveKeyword_2_0; }
		
		//'difficulty'
		public Keyword getDifficultyKeyword_3() { return cDifficultyKeyword_3; }
		
		//difficulty=Difficulty
		public Assignment getDifficultyAssignment_4() { return cDifficultyAssignment_4; }
		
		//Difficulty
		public RuleCall getDifficultyDifficultyEnumRuleCall_4_0() { return cDifficultyDifficultyEnumRuleCall_4_0; }
		
		//('timeLimit' timeLimit=EDoubleObject)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'timeLimit'
		public Keyword getTimeLimitKeyword_5_0() { return cTimeLimitKeyword_5_0; }
		
		//timeLimit=EDoubleObject
		public Assignment getTimeLimitAssignment_5_1() { return cTimeLimitAssignment_5_1; }
		
		//EDoubleObject
		public RuleCall getTimeLimitEDoubleObjectParserRuleCall_5_1_0() { return cTimeLimitEDoubleObjectParserRuleCall_5_1_0; }
		
		//'retries'
		public Keyword getRetriesKeyword_6() { return cRetriesKeyword_6; }
		
		//retries=EInt
		public Assignment getRetriesAssignment_7() { return cRetriesAssignment_7; }
		
		//EInt
		public RuleCall getRetriesEIntParserRuleCall_7_0() { return cRetriesEIntParserRuleCall_7_0; }
		
		//'sentence'
		public Keyword getSentenceKeyword_8() { return cSentenceKeyword_8; }
		
		//sentence=EString
		public Assignment getSentenceAssignment_9() { return cSentenceAssignment_9; }
		
		//EString
		public RuleCall getSentenceEStringParserRuleCall_9_0() { return cSentenceEStringParserRuleCall_9_0; }
		
		//'result'
		public Keyword getResultKeyword_10() { return cResultKeyword_10; }
		
		//result=EventResult
		public Assignment getResultAssignment_11() { return cResultAssignment_11; }
		
		//EventResult
		public RuleCall getResultEventResultParserRuleCall_11_0() { return cResultEventResultParserRuleCall_11_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class QuestionEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.rf.RealmForgeDsl.QuestionEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cQuestionEventKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cDifficultyKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDifficultyAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDifficultyDifficultyEnumRuleCall_3_0 = (RuleCall)cDifficultyAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTimeLimitKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTimeLimitAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTimeLimitEDoubleObjectParserRuleCall_4_1_0 = (RuleCall)cTimeLimitAssignment_4_1.eContents().get(0);
		private final Keyword cRetriesKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cRetriesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cRetriesEIntParserRuleCall_6_0 = (RuleCall)cRetriesAssignment_6.eContents().get(0);
		private final Keyword cQuestionKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cQuestionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cQuestionEStringParserRuleCall_8_0 = (RuleCall)cQuestionAssignment_8.eContents().get(0);
		private final Keyword cResultKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cResultAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cResultEventResultParserRuleCall_10_0 = (RuleCall)cResultAssignment_10.eContents().get(0);
		private final Keyword cOptionsKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cLeftCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cOptionsAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cOptionsOptionParserRuleCall_13_0 = (RuleCall)cOptionsAssignment_13.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cCommaKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cOptionsAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final RuleCall cOptionsOptionParserRuleCall_14_1_0 = (RuleCall)cOptionsAssignment_14_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		
		//QuestionEvent returns QuestionEvent:
		//    'QuestionEvent'
		//    '{'
		//        'difficulty' difficulty=Difficulty
		//        ('timeLimit' timeLimit=EDoubleObject)?
		//        'retries' retries=EInt
		//        'question' question=EString
		//        'result' result=EventResult
		//        'options' '{' options+=Option ( "," options+=Option)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'QuestionEvent'
		//'{'
		//    'difficulty' difficulty=Difficulty
		//    ('timeLimit' timeLimit=EDoubleObject)?
		//    'retries' retries=EInt
		//    'question' question=EString
		//    'result' result=EventResult
		//    'options' '{' options+=Option ( "," options+=Option)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'QuestionEvent'
		public Keyword getQuestionEventKeyword_0() { return cQuestionEventKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'difficulty'
		public Keyword getDifficultyKeyword_2() { return cDifficultyKeyword_2; }
		
		//difficulty=Difficulty
		public Assignment getDifficultyAssignment_3() { return cDifficultyAssignment_3; }
		
		//Difficulty
		public RuleCall getDifficultyDifficultyEnumRuleCall_3_0() { return cDifficultyDifficultyEnumRuleCall_3_0; }
		
		//('timeLimit' timeLimit=EDoubleObject)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'timeLimit'
		public Keyword getTimeLimitKeyword_4_0() { return cTimeLimitKeyword_4_0; }
		
		//timeLimit=EDoubleObject
		public Assignment getTimeLimitAssignment_4_1() { return cTimeLimitAssignment_4_1; }
		
		//EDoubleObject
		public RuleCall getTimeLimitEDoubleObjectParserRuleCall_4_1_0() { return cTimeLimitEDoubleObjectParserRuleCall_4_1_0; }
		
		//'retries'
		public Keyword getRetriesKeyword_5() { return cRetriesKeyword_5; }
		
		//retries=EInt
		public Assignment getRetriesAssignment_6() { return cRetriesAssignment_6; }
		
		//EInt
		public RuleCall getRetriesEIntParserRuleCall_6_0() { return cRetriesEIntParserRuleCall_6_0; }
		
		//'question'
		public Keyword getQuestionKeyword_7() { return cQuestionKeyword_7; }
		
		//question=EString
		public Assignment getQuestionAssignment_8() { return cQuestionAssignment_8; }
		
		//EString
		public RuleCall getQuestionEStringParserRuleCall_8_0() { return cQuestionEStringParserRuleCall_8_0; }
		
		//'result'
		public Keyword getResultKeyword_9() { return cResultKeyword_9; }
		
		//result=EventResult
		public Assignment getResultAssignment_10() { return cResultAssignment_10; }
		
		//EventResult
		public RuleCall getResultEventResultParserRuleCall_10_0() { return cResultEventResultParserRuleCall_10_0; }
		
		//'options'
		public Keyword getOptionsKeyword_11() { return cOptionsKeyword_11; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_12() { return cLeftCurlyBracketKeyword_12; }
		
		//options+=Option
		public Assignment getOptionsAssignment_13() { return cOptionsAssignment_13; }
		
		//Option
		public RuleCall getOptionsOptionParserRuleCall_13_0() { return cOptionsOptionParserRuleCall_13_0; }
		
		//( "," options+=Option)*
		public Group getGroup_14() { return cGroup_14; }
		
		//","
		public Keyword getCommaKeyword_14_0() { return cCommaKeyword_14_0; }
		
		//options+=Option
		public Assignment getOptionsAssignment_14_1() { return cOptionsAssignment_14_1; }
		
		//Option
		public RuleCall getOptionsOptionParserRuleCall_14_1_0() { return cOptionsOptionParserRuleCall_14_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
	}
	public class OptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.rf.RealmForgeDsl.Option");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTextKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextEStringParserRuleCall_2_0 = (RuleCall)cTextAssignment_2.eContents().get(0);
		private final Assignment cIsCorrectAnswerAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cIsCorrectAnswerIsCorrectAnswerKeyword_3_0 = (Keyword)cIsCorrectAnswerAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Option returns Option:
		//    '{'
		//    'text' text=EString
		//    (isCorrectAnswer?='isCorrectAnswer')?
		//  '}';
		@Override public ParserRule getRule() { return rule; }
		
		//  '{'
		//  'text' text=EString
		//  (isCorrectAnswer?='isCorrectAnswer')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//'text'
		public Keyword getTextKeyword_1() { return cTextKeyword_1; }
		
		//text=EString
		public Assignment getTextAssignment_2() { return cTextAssignment_2; }
		
		//EString
		public RuleCall getTextEStringParserRuleCall_2_0() { return cTextEStringParserRuleCall_2_0; }
		
		//(isCorrectAnswer?='isCorrectAnswer')?
		public Assignment getIsCorrectAnswerAssignment_3() { return cIsCorrectAnswerAssignment_3; }
		
		//'isCorrectAnswer'
		public Keyword getIsCorrectAnswerIsCorrectAnswerKeyword_3_0() { return cIsCorrectAnswerIsCorrectAnswerKeyword_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	public class DifficultyElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.rf.RealmForgeDsl.Difficulty");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cEASYEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cEASYEASYKeyword_0_0 = (Keyword)cEASYEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNORMALEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNORMALNORMALKeyword_1_0 = (Keyword)cNORMALEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cHARDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cHARDHARDKeyword_2_0 = (Keyword)cHARDEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Difficulty returns Difficulty:
		//                EASY = 'EASY' | NORMAL = 'NORMAL' | HARD = 'HARD';
		public EnumRule getRule() { return rule; }
		
		//EASY = 'EASY' | NORMAL = 'NORMAL' | HARD = 'HARD'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//EASY = 'EASY'
		public EnumLiteralDeclaration getEASYEnumLiteralDeclaration_0() { return cEASYEnumLiteralDeclaration_0; }
		
		//'EASY'
		public Keyword getEASYEASYKeyword_0_0() { return cEASYEASYKeyword_0_0; }
		
		//NORMAL = 'NORMAL'
		public EnumLiteralDeclaration getNORMALEnumLiteralDeclaration_1() { return cNORMALEnumLiteralDeclaration_1; }
		
		//'NORMAL'
		public Keyword getNORMALNORMALKeyword_1_0() { return cNORMALNORMALKeyword_1_0; }
		
		//HARD = 'HARD'
		public EnumLiteralDeclaration getHARDEnumLiteralDeclaration_2() { return cHARDEnumLiteralDeclaration_2; }
		
		//'HARD'
		public Keyword getHARDHARDKeyword_2_0() { return cHARDHARDKeyword_2_0; }
	}
	
	private final EventPackElements pEventPack;
	private final EventElements pEvent;
	private final EStringElements pEString;
	private final DifficultyElements eDifficulty;
	private final EBooleanElements pEBoolean;
	private final EDoubleObjectElements pEDoubleObject;
	private final EIntElements pEInt;
	private final EventResultElements pEventResult;
	private final TypeRacerEventElements pTypeRacerEvent;
	private final QuestionEventElements pQuestionEvent;
	private final OptionElements pOption;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RealmForgeDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pEventPack = new EventPackElements();
		this.pEvent = new EventElements();
		this.pEString = new EStringElements();
		this.eDifficulty = new DifficultyElements();
		this.pEBoolean = new EBooleanElements();
		this.pEDoubleObject = new EDoubleObjectElements();
		this.pEInt = new EIntElements();
		this.pEventResult = new EventResultElements();
		this.pTypeRacerEvent = new TypeRacerEventElements();
		this.pQuestionEvent = new QuestionEventElements();
		this.pOption = new OptionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("no.ntnu.tdt4250.rf.RealmForgeDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//EventPack returns EventPack:
	//    'name' name=EString
	//    'description' description=EString
	//    'unit' unit=EString
	//    (events+=Event)*
	//    ;
	public EventPackElements getEventPackAccess() {
		return pEventPack;
	}
	
	public ParserRule getEventPackRule() {
		return getEventPackAccess().getRule();
	}
	
	//Event returns Event:
	//    TypeRacerEvent | QuestionEvent;
	public EventElements getEventAccess() {
		return pEvent;
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//enum Difficulty returns Difficulty:
	//                EASY = 'EASY' | NORMAL = 'NORMAL' | HARD = 'HARD';
	public DifficultyElements getDifficultyAccess() {
		return eDifficulty;
	}
	
	public EnumRule getDifficultyRule() {
		return getDifficultyAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//EDoubleObject returns ecore::EDoubleObject:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public EDoubleObjectElements getEDoubleObjectAccess() {
		return pEDoubleObject;
	}
	
	public ParserRule getEDoubleObjectRule() {
		return getEDoubleObjectAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EventResult returns EventResult:
	//    {EventResult}
	//    '{'
	//        ('message' message=EString)?
	//    '}';
	public EventResultElements getEventResultAccess() {
		return pEventResult;
	}
	
	public ParserRule getEventResultRule() {
		return getEventResultAccess().getRule();
	}
	
	//TypeRacerEvent returns TypeRacerEvent:
	//    'TypeRacerEvent'
	//    '{'
	//        (isCaseSensitive?='isCaseSensitive')?
	//        'difficulty' difficulty=Difficulty
	//        ('timeLimit' timeLimit=EDoubleObject)?
	//        'retries' retries=EInt
	//        'sentence' sentence=EString
	//        'result' result=EventResult
	//    '}';
	public TypeRacerEventElements getTypeRacerEventAccess() {
		return pTypeRacerEvent;
	}
	
	public ParserRule getTypeRacerEventRule() {
		return getTypeRacerEventAccess().getRule();
	}
	
	//QuestionEvent returns QuestionEvent:
	//    'QuestionEvent'
	//    '{'
	//        'difficulty' difficulty=Difficulty
	//        ('timeLimit' timeLimit=EDoubleObject)?
	//        'retries' retries=EInt
	//        'question' question=EString
	//        'result' result=EventResult
	//        'options' '{' options+=Option ( "," options+=Option)* '}'
	//    '}';
	public QuestionEventElements getQuestionEventAccess() {
		return pQuestionEvent;
	}
	
	public ParserRule getQuestionEventRule() {
		return getQuestionEventAccess().getRule();
	}
	
	//Option returns Option:
	//    '{'
	//    'text' text=EString
	//    (isCorrectAnswer?='isCorrectAnswer')?
	//  '}';
	public OptionElements getOptionAccess() {
		return pOption;
	}
	
	public ParserRule getOptionRule() {
		return getOptionAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
