/*
 * generated by Xtext 2.40.0
 */
package no.ntnu.tdt4250.rf.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import no.ntnu.tdt4250.rf.ide.contentassist.antlr.internal.InternalRealmForgeDslParser;
import no.ntnu.tdt4250.rf.services.RealmForgeDslGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class RealmForgeDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(RealmForgeDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, RealmForgeDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEventAccess().getAlternatives(), "rule__Event__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getEDoubleObjectAccess().getAlternatives_4_0(), "rule__EDoubleObject__Alternatives_4_0");
			builder.put(grammarAccess.getDifficultyAccess().getAlternatives(), "rule__Difficulty__Alternatives");
			builder.put(grammarAccess.getEventPackAccess().getGroup(), "rule__EventPack__Group__0");
			builder.put(grammarAccess.getEDoubleObjectAccess().getGroup(), "rule__EDoubleObject__Group__0");
			builder.put(grammarAccess.getEDoubleObjectAccess().getGroup_4(), "rule__EDoubleObject__Group_4__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getEventResultAccess().getGroup(), "rule__EventResult__Group__0");
			builder.put(grammarAccess.getEventResultAccess().getGroup_2(), "rule__EventResult__Group_2__0");
			builder.put(grammarAccess.getTypeRacerEventAccess().getGroup(), "rule__TypeRacerEvent__Group__0");
			builder.put(grammarAccess.getTypeRacerEventAccess().getGroup_5(), "rule__TypeRacerEvent__Group_5__0");
			builder.put(grammarAccess.getQuestionEventAccess().getGroup(), "rule__QuestionEvent__Group__0");
			builder.put(grammarAccess.getQuestionEventAccess().getGroup_4(), "rule__QuestionEvent__Group_4__0");
			builder.put(grammarAccess.getQuestionEventAccess().getGroup_14(), "rule__QuestionEvent__Group_14__0");
			builder.put(grammarAccess.getOptionAccess().getGroup(), "rule__Option__Group__0");
			builder.put(grammarAccess.getEventPackAccess().getNameAssignment_1(), "rule__EventPack__NameAssignment_1");
			builder.put(grammarAccess.getEventPackAccess().getDescriptionAssignment_3(), "rule__EventPack__DescriptionAssignment_3");
			builder.put(grammarAccess.getEventPackAccess().getUnitAssignment_5(), "rule__EventPack__UnitAssignment_5");
			builder.put(grammarAccess.getEventPackAccess().getEventsAssignment_6(), "rule__EventPack__EventsAssignment_6");
			builder.put(grammarAccess.getEventResultAccess().getMessageAssignment_2_1(), "rule__EventResult__MessageAssignment_2_1");
			builder.put(grammarAccess.getTypeRacerEventAccess().getIsCaseSensitiveAssignment_2(), "rule__TypeRacerEvent__IsCaseSensitiveAssignment_2");
			builder.put(grammarAccess.getTypeRacerEventAccess().getDifficultyAssignment_4(), "rule__TypeRacerEvent__DifficultyAssignment_4");
			builder.put(grammarAccess.getTypeRacerEventAccess().getTimeLimitAssignment_5_1(), "rule__TypeRacerEvent__TimeLimitAssignment_5_1");
			builder.put(grammarAccess.getTypeRacerEventAccess().getRetriesAssignment_7(), "rule__TypeRacerEvent__RetriesAssignment_7");
			builder.put(grammarAccess.getTypeRacerEventAccess().getSentenceAssignment_9(), "rule__TypeRacerEvent__SentenceAssignment_9");
			builder.put(grammarAccess.getTypeRacerEventAccess().getResultAssignment_11(), "rule__TypeRacerEvent__ResultAssignment_11");
			builder.put(grammarAccess.getQuestionEventAccess().getDifficultyAssignment_3(), "rule__QuestionEvent__DifficultyAssignment_3");
			builder.put(grammarAccess.getQuestionEventAccess().getTimeLimitAssignment_4_1(), "rule__QuestionEvent__TimeLimitAssignment_4_1");
			builder.put(grammarAccess.getQuestionEventAccess().getRetriesAssignment_6(), "rule__QuestionEvent__RetriesAssignment_6");
			builder.put(grammarAccess.getQuestionEventAccess().getQuestionAssignment_8(), "rule__QuestionEvent__QuestionAssignment_8");
			builder.put(grammarAccess.getQuestionEventAccess().getResultAssignment_10(), "rule__QuestionEvent__ResultAssignment_10");
			builder.put(grammarAccess.getQuestionEventAccess().getOptionsAssignment_13(), "rule__QuestionEvent__OptionsAssignment_13");
			builder.put(grammarAccess.getQuestionEventAccess().getOptionsAssignment_14_1(), "rule__QuestionEvent__OptionsAssignment_14_1");
			builder.put(grammarAccess.getOptionAccess().getTextAssignment_2(), "rule__Option__TextAssignment_2");
			builder.put(grammarAccess.getOptionAccess().getIsCorrectAnswerAssignment_3(), "rule__Option__IsCorrectAnswerAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private RealmForgeDslGrammarAccess grammarAccess;

	@Override
	protected InternalRealmForgeDslParser createParser() {
		InternalRealmForgeDslParser result = new InternalRealmForgeDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RealmForgeDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RealmForgeDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
