/*
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.rf.formatting2

import com.google.inject.Inject
import no.ntnu.tdt4250.rf.EventPack
import no.ntnu.tdt4250.rf.TypeRacerEvent
import no.ntnu.tdt4250.rf.services.RealmForgeDslGrammarAccess
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument

class RealmForgeDslFormatter extends AbstractFormatter2 {
	
	@Inject extension RealmForgeDslGrammarAccess

	def dispatch void format(EventPack eventPack, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (event : eventPack.events) {
			event.format
		}
	}

	def dispatch void format(TypeRacerEvent typeRacerEvent, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		typeRacerEvent.result.format
	}
	
	// TODO: implement for QuestionEvent
}
