/*
 * generated by Xtext 2.40.0
 */
grammar InternalRealmForgeDsl;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package no.ntnu.tdt4250.rf.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package no.ntnu.tdt4250.rf.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import no.ntnu.tdt4250.rf.services.RealmForgeDslGrammarAccess;

}
@parser::members {
	private RealmForgeDslGrammarAccess grammarAccess;

	public void setGrammarAccess(RealmForgeDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleEventPack
entryRuleEventPack
:
{ before(grammarAccess.getEventPackRule()); }
	 ruleEventPack
{ after(grammarAccess.getEventPackRule()); } 
	 EOF 
;

// Rule EventPack
ruleEventPack 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEventPackAccess().getGroup()); }
		(rule__EventPack__Group__0)
		{ after(grammarAccess.getEventPackAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEvent
entryRuleEvent
:
{ before(grammarAccess.getEventRule()); }
	 ruleEvent
{ after(grammarAccess.getEventRule()); } 
	 EOF 
;

// Rule Event
ruleEvent 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEventAccess().getAlternatives()); }
		(rule__Event__Alternatives)
		{ after(grammarAccess.getEventAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEString
entryRuleEString
:
{ before(grammarAccess.getEStringRule()); }
	 ruleEString
{ after(grammarAccess.getEStringRule()); } 
	 EOF 
;

// Rule EString
ruleEString 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEStringAccess().getAlternatives()); }
		(rule__EString__Alternatives)
		{ after(grammarAccess.getEStringAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEDoubleObject
entryRuleEDoubleObject
:
{ before(grammarAccess.getEDoubleObjectRule()); }
	 ruleEDoubleObject
{ after(grammarAccess.getEDoubleObjectRule()); } 
	 EOF 
;

// Rule EDoubleObject
ruleEDoubleObject 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEDoubleObjectAccess().getGroup()); }
		(rule__EDoubleObject__Group__0)
		{ after(grammarAccess.getEDoubleObjectAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEInt
entryRuleEInt
:
{ before(grammarAccess.getEIntRule()); }
	 ruleEInt
{ after(grammarAccess.getEIntRule()); } 
	 EOF 
;

// Rule EInt
ruleEInt 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEIntAccess().getGroup()); }
		(rule__EInt__Group__0)
		{ after(grammarAccess.getEIntAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEventResult
entryRuleEventResult
:
{ before(grammarAccess.getEventResultRule()); }
	 ruleEventResult
{ after(grammarAccess.getEventResultRule()); } 
	 EOF 
;

// Rule EventResult
ruleEventResult 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEventResultAccess().getGroup()); }
		(rule__EventResult__Group__0)
		{ after(grammarAccess.getEventResultAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleTypeRacerEvent
entryRuleTypeRacerEvent
:
{ before(grammarAccess.getTypeRacerEventRule()); }
	 ruleTypeRacerEvent
{ after(grammarAccess.getTypeRacerEventRule()); } 
	 EOF 
;

// Rule TypeRacerEvent
ruleTypeRacerEvent 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getTypeRacerEventAccess().getGroup()); }
		(rule__TypeRacerEvent__Group__0)
		{ after(grammarAccess.getTypeRacerEventAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleQuestionEvent
entryRuleQuestionEvent
:
{ before(grammarAccess.getQuestionEventRule()); }
	 ruleQuestionEvent
{ after(grammarAccess.getQuestionEventRule()); } 
	 EOF 
;

// Rule QuestionEvent
ruleQuestionEvent 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getQuestionEventAccess().getGroup()); }
		(rule__QuestionEvent__Group__0)
		{ after(grammarAccess.getQuestionEventAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleOption
entryRuleOption
:
{ before(grammarAccess.getOptionRule()); }
	 ruleOption
{ after(grammarAccess.getOptionRule()); } 
	 EOF 
;

// Rule Option
ruleOption 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getOptionAccess().getGroup()); }
		(rule__Option__Group__0)
		{ after(grammarAccess.getOptionAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Rule Difficulty
ruleDifficulty
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDifficultyAccess().getAlternatives()); }
		(rule__Difficulty__Alternatives)
		{ after(grammarAccess.getDifficultyAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Event__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventAccess().getTypeRacerEventParserRuleCall_0()); }
		ruleTypeRacerEvent
		{ after(grammarAccess.getEventAccess().getTypeRacerEventParserRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getEventAccess().getQuestionEventParserRuleCall_1()); }
		ruleQuestionEvent
		{ after(grammarAccess.getEventAccess().getQuestionEventParserRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EString__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0()); }
		RULE_STRING
		{ after(grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getEStringAccess().getIDTerminalRuleCall_1()); }
		RULE_ID
		{ after(grammarAccess.getEStringAccess().getIDTerminalRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Alternatives_4_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEDoubleObjectAccess().getEKeyword_4_0_0()); }
		'E'
		{ after(grammarAccess.getEDoubleObjectAccess().getEKeyword_4_0_0()); }
	)
	|
	(
		{ before(grammarAccess.getEDoubleObjectAccess().getEKeyword_4_0_1()); }
		'e'
		{ after(grammarAccess.getEDoubleObjectAccess().getEKeyword_4_0_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Difficulty__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDifficultyAccess().getEASYEnumLiteralDeclaration_0()); }
		('EASY')
		{ after(grammarAccess.getDifficultyAccess().getEASYEnumLiteralDeclaration_0()); }
	)
	|
	(
		{ before(grammarAccess.getDifficultyAccess().getNORMALEnumLiteralDeclaration_1()); }
		('NORMAL')
		{ after(grammarAccess.getDifficultyAccess().getNORMALEnumLiteralDeclaration_1()); }
	)
	|
	(
		{ before(grammarAccess.getDifficultyAccess().getHARDEnumLiteralDeclaration_2()); }
		('HARD')
		{ after(grammarAccess.getDifficultyAccess().getHARDEnumLiteralDeclaration_2()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventPack__Group__0__Impl
	rule__EventPack__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventPackAccess().getNameKeyword_0()); }
	'name'
	{ after(grammarAccess.getEventPackAccess().getNameKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventPack__Group__1__Impl
	rule__EventPack__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventPackAccess().getNameAssignment_1()); }
	(rule__EventPack__NameAssignment_1)
	{ after(grammarAccess.getEventPackAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventPack__Group__2__Impl
	rule__EventPack__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventPackAccess().getDescriptionKeyword_2()); }
	'description'
	{ after(grammarAccess.getEventPackAccess().getDescriptionKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventPack__Group__3__Impl
	rule__EventPack__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventPackAccess().getDescriptionAssignment_3()); }
	(rule__EventPack__DescriptionAssignment_3)
	{ after(grammarAccess.getEventPackAccess().getDescriptionAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventPack__Group__4__Impl
	rule__EventPack__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventPackAccess().getUnitKeyword_4()); }
	'unit'
	{ after(grammarAccess.getEventPackAccess().getUnitKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventPack__Group__5__Impl
	rule__EventPack__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventPackAccess().getUnitAssignment_5()); }
	(rule__EventPack__UnitAssignment_5)
	{ after(grammarAccess.getEventPackAccess().getUnitAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventPack__Group__6__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventPackAccess().getEventsAssignment_6()); }
	(rule__EventPack__EventsAssignment_6)*
	{ after(grammarAccess.getEventPackAccess().getEventsAssignment_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EDoubleObject__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDoubleObject__Group__0__Impl
	rule__EDoubleObject__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleObjectAccess().getHyphenMinusKeyword_0()); }
	('-')?
	{ after(grammarAccess.getEDoubleObjectAccess().getHyphenMinusKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDoubleObject__Group__1__Impl
	rule__EDoubleObject__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleObjectAccess().getINTTerminalRuleCall_1()); }
	(RULE_INT)?
	{ after(grammarAccess.getEDoubleObjectAccess().getINTTerminalRuleCall_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDoubleObject__Group__2__Impl
	rule__EDoubleObject__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleObjectAccess().getFullStopKeyword_2()); }
	'.'
	{ after(grammarAccess.getEDoubleObjectAccess().getFullStopKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDoubleObject__Group__3__Impl
	rule__EDoubleObject__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleObjectAccess().getINTTerminalRuleCall_3()); }
	RULE_INT
	{ after(grammarAccess.getEDoubleObjectAccess().getINTTerminalRuleCall_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDoubleObject__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleObjectAccess().getGroup_4()); }
	(rule__EDoubleObject__Group_4__0)?
	{ after(grammarAccess.getEDoubleObjectAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EDoubleObject__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDoubleObject__Group_4__0__Impl
	rule__EDoubleObject__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleObjectAccess().getAlternatives_4_0()); }
	(rule__EDoubleObject__Alternatives_4_0)
	{ after(grammarAccess.getEDoubleObjectAccess().getAlternatives_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDoubleObject__Group_4__1__Impl
	rule__EDoubleObject__Group_4__2
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleObjectAccess().getHyphenMinusKeyword_4_1()); }
	('-')?
	{ after(grammarAccess.getEDoubleObjectAccess().getHyphenMinusKeyword_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group_4__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDoubleObject__Group_4__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group_4__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleObjectAccess().getINTTerminalRuleCall_4_2()); }
	RULE_INT
	{ after(grammarAccess.getEDoubleObjectAccess().getINTTerminalRuleCall_4_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EInt__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EInt__Group__0__Impl
	rule__EInt__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EInt__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEIntAccess().getHyphenMinusKeyword_0()); }
	('-')?
	{ after(grammarAccess.getEIntAccess().getHyphenMinusKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EInt__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EInt__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EInt__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEIntAccess().getINTTerminalRuleCall_1()); }
	RULE_INT
	{ after(grammarAccess.getEIntAccess().getINTTerminalRuleCall_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EventResult__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventResult__Group__0__Impl
	rule__EventResult__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EventResult__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventResultAccess().getEventResultAction_0()); }
	()
	{ after(grammarAccess.getEventResultAccess().getEventResultAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventResult__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventResult__Group__1__Impl
	rule__EventResult__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__EventResult__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventResultAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getEventResultAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventResult__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventResult__Group__2__Impl
	rule__EventResult__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__EventResult__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventResultAccess().getGroup_2()); }
	(rule__EventResult__Group_2__0)?
	{ after(grammarAccess.getEventResultAccess().getGroup_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventResult__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventResult__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EventResult__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventResultAccess().getRightCurlyBracketKeyword_3()); }
	'}'
	{ after(grammarAccess.getEventResultAccess().getRightCurlyBracketKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EventResult__Group_2__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventResult__Group_2__0__Impl
	rule__EventResult__Group_2__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EventResult__Group_2__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventResultAccess().getMessageKeyword_2_0()); }
	'message'
	{ after(grammarAccess.getEventResultAccess().getMessageKeyword_2_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventResult__Group_2__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EventResult__Group_2__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EventResult__Group_2__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEventResultAccess().getMessageAssignment_2_1()); }
	(rule__EventResult__MessageAssignment_2_1)
	{ after(grammarAccess.getEventResultAccess().getMessageAssignment_2_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__TypeRacerEvent__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group__0__Impl
	rule__TypeRacerEvent__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getTypeRacerEventKeyword_0()); }
	'TypeRacerEvent'
	{ after(grammarAccess.getTypeRacerEventAccess().getTypeRacerEventKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group__1__Impl
	rule__TypeRacerEvent__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getTypeRacerEventAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group__2__Impl
	rule__TypeRacerEvent__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getIsCaseSensitiveAssignment_2()); }
	(rule__TypeRacerEvent__IsCaseSensitiveAssignment_2)?
	{ after(grammarAccess.getTypeRacerEventAccess().getIsCaseSensitiveAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group__3__Impl
	rule__TypeRacerEvent__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getDifficultyKeyword_3()); }
	'difficulty'
	{ after(grammarAccess.getTypeRacerEventAccess().getDifficultyKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group__4__Impl
	rule__TypeRacerEvent__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getDifficultyAssignment_4()); }
	(rule__TypeRacerEvent__DifficultyAssignment_4)
	{ after(grammarAccess.getTypeRacerEventAccess().getDifficultyAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group__5__Impl
	rule__TypeRacerEvent__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getGroup_5()); }
	(rule__TypeRacerEvent__Group_5__0)?
	{ after(grammarAccess.getTypeRacerEventAccess().getGroup_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group__6__Impl
	rule__TypeRacerEvent__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getRetriesKeyword_6()); }
	'retries'
	{ after(grammarAccess.getTypeRacerEventAccess().getRetriesKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group__7__Impl
	rule__TypeRacerEvent__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getRetriesAssignment_7()); }
	(rule__TypeRacerEvent__RetriesAssignment_7)
	{ after(grammarAccess.getTypeRacerEventAccess().getRetriesAssignment_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group__8__Impl
	rule__TypeRacerEvent__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getSentenceKeyword_8()); }
	'sentence'
	{ after(grammarAccess.getTypeRacerEventAccess().getSentenceKeyword_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group__9__Impl
	rule__TypeRacerEvent__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getSentenceAssignment_9()); }
	(rule__TypeRacerEvent__SentenceAssignment_9)
	{ after(grammarAccess.getTypeRacerEventAccess().getSentenceAssignment_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group__10__Impl
	rule__TypeRacerEvent__Group__11
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getResultKeyword_10()); }
	'result'
	{ after(grammarAccess.getTypeRacerEventAccess().getResultKeyword_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__11
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group__11__Impl
	rule__TypeRacerEvent__Group__12
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__11__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getResultAssignment_11()); }
	(rule__TypeRacerEvent__ResultAssignment_11)
	{ after(grammarAccess.getTypeRacerEventAccess().getResultAssignment_11()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__12
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group__12__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group__12__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getRightCurlyBracketKeyword_12()); }
	'}'
	{ after(grammarAccess.getTypeRacerEventAccess().getRightCurlyBracketKeyword_12()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__TypeRacerEvent__Group_5__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group_5__0__Impl
	rule__TypeRacerEvent__Group_5__1
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group_5__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getTimeLimitKeyword_5_0()); }
	'timeLimit'
	{ after(grammarAccess.getTypeRacerEventAccess().getTimeLimitKeyword_5_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group_5__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__TypeRacerEvent__Group_5__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__Group_5__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTypeRacerEventAccess().getTimeLimitAssignment_5_1()); }
	(rule__TypeRacerEvent__TimeLimitAssignment_5_1)
	{ after(grammarAccess.getTypeRacerEventAccess().getTimeLimitAssignment_5_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__QuestionEvent__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__0__Impl
	rule__QuestionEvent__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getQuestionEventKeyword_0()); }
	'QuestionEvent'
	{ after(grammarAccess.getQuestionEventAccess().getQuestionEventKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__1__Impl
	rule__QuestionEvent__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getQuestionEventAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__2__Impl
	rule__QuestionEvent__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getDifficultyKeyword_2()); }
	'difficulty'
	{ after(grammarAccess.getQuestionEventAccess().getDifficultyKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__3__Impl
	rule__QuestionEvent__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getDifficultyAssignment_3()); }
	(rule__QuestionEvent__DifficultyAssignment_3)
	{ after(grammarAccess.getQuestionEventAccess().getDifficultyAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__4__Impl
	rule__QuestionEvent__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getGroup_4()); }
	(rule__QuestionEvent__Group_4__0)?
	{ after(grammarAccess.getQuestionEventAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__5__Impl
	rule__QuestionEvent__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getRetriesKeyword_5()); }
	'retries'
	{ after(grammarAccess.getQuestionEventAccess().getRetriesKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__6__Impl
	rule__QuestionEvent__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getRetriesAssignment_6()); }
	(rule__QuestionEvent__RetriesAssignment_6)
	{ after(grammarAccess.getQuestionEventAccess().getRetriesAssignment_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__7__Impl
	rule__QuestionEvent__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getQuestionKeyword_7()); }
	'question'
	{ after(grammarAccess.getQuestionEventAccess().getQuestionKeyword_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__8__Impl
	rule__QuestionEvent__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getQuestionAssignment_8()); }
	(rule__QuestionEvent__QuestionAssignment_8)
	{ after(grammarAccess.getQuestionEventAccess().getQuestionAssignment_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__9__Impl
	rule__QuestionEvent__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getResultKeyword_9()); }
	'result'
	{ after(grammarAccess.getQuestionEventAccess().getResultKeyword_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__10__Impl
	rule__QuestionEvent__Group__11
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getResultAssignment_10()); }
	(rule__QuestionEvent__ResultAssignment_10)
	{ after(grammarAccess.getQuestionEventAccess().getResultAssignment_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__11
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__11__Impl
	rule__QuestionEvent__Group__12
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__11__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getOptionsKeyword_11()); }
	'options'
	{ after(grammarAccess.getQuestionEventAccess().getOptionsKeyword_11()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__12
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__12__Impl
	rule__QuestionEvent__Group__13
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__12__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getLeftCurlyBracketKeyword_12()); }
	'{'
	{ after(grammarAccess.getQuestionEventAccess().getLeftCurlyBracketKeyword_12()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__13
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__13__Impl
	rule__QuestionEvent__Group__14
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__13__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getOptionsAssignment_13()); }
	(rule__QuestionEvent__OptionsAssignment_13)
	{ after(grammarAccess.getQuestionEventAccess().getOptionsAssignment_13()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__14
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__14__Impl
	rule__QuestionEvent__Group__15
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__14__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getGroup_14()); }
	(rule__QuestionEvent__Group_14__0)*
	{ after(grammarAccess.getQuestionEventAccess().getGroup_14()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__15
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__15__Impl
	rule__QuestionEvent__Group__16
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__15__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getRightCurlyBracketKeyword_15()); }
	'}'
	{ after(grammarAccess.getQuestionEventAccess().getRightCurlyBracketKeyword_15()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__16
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group__16__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group__16__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getRightCurlyBracketKeyword_16()); }
	'}'
	{ after(grammarAccess.getQuestionEventAccess().getRightCurlyBracketKeyword_16()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__QuestionEvent__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group_4__0__Impl
	rule__QuestionEvent__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getTimeLimitKeyword_4_0()); }
	'timeLimit'
	{ after(grammarAccess.getQuestionEventAccess().getTimeLimitKeyword_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getTimeLimitAssignment_4_1()); }
	(rule__QuestionEvent__TimeLimitAssignment_4_1)
	{ after(grammarAccess.getQuestionEventAccess().getTimeLimitAssignment_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__QuestionEvent__Group_14__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group_14__0__Impl
	rule__QuestionEvent__Group_14__1
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group_14__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getCommaKeyword_14_0()); }
	','
	{ after(grammarAccess.getQuestionEventAccess().getCommaKeyword_14_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group_14__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QuestionEvent__Group_14__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__Group_14__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQuestionEventAccess().getOptionsAssignment_14_1()); }
	(rule__QuestionEvent__OptionsAssignment_14_1)
	{ after(grammarAccess.getQuestionEventAccess().getOptionsAssignment_14_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Option__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Option__Group__0__Impl
	rule__Option__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Option__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOptionAccess().getLeftCurlyBracketKeyword_0()); }
	'{'
	{ after(grammarAccess.getOptionAccess().getLeftCurlyBracketKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Option__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Option__Group__1__Impl
	rule__Option__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Option__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOptionAccess().getTextKeyword_1()); }
	'text'
	{ after(grammarAccess.getOptionAccess().getTextKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Option__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Option__Group__2__Impl
	rule__Option__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Option__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOptionAccess().getTextAssignment_2()); }
	(rule__Option__TextAssignment_2)
	{ after(grammarAccess.getOptionAccess().getTextAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Option__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Option__Group__3__Impl
	rule__Option__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Option__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOptionAccess().getIsCorrectAnswerAssignment_3()); }
	(rule__Option__IsCorrectAnswerAssignment_3)?
	{ after(grammarAccess.getOptionAccess().getIsCorrectAnswerAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Option__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Option__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Option__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOptionAccess().getRightCurlyBracketKeyword_4()); }
	'}'
	{ after(grammarAccess.getOptionAccess().getRightCurlyBracketKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EventPack__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventPackAccess().getNameEStringParserRuleCall_1_0()); }
		ruleEString
		{ after(grammarAccess.getEventPackAccess().getNameEStringParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__DescriptionAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventPackAccess().getDescriptionEStringParserRuleCall_3_0()); }
		ruleEString
		{ after(grammarAccess.getEventPackAccess().getDescriptionEStringParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__UnitAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventPackAccess().getUnitEStringParserRuleCall_5_0()); }
		ruleEString
		{ after(grammarAccess.getEventPackAccess().getUnitEStringParserRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventPack__EventsAssignment_6
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventPackAccess().getEventsEventParserRuleCall_6_0()); }
		ruleEvent
		{ after(grammarAccess.getEventPackAccess().getEventsEventParserRuleCall_6_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EventResult__MessageAssignment_2_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEventResultAccess().getMessageEStringParserRuleCall_2_1_0()); }
		ruleEString
		{ after(grammarAccess.getEventResultAccess().getMessageEStringParserRuleCall_2_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__IsCaseSensitiveAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTypeRacerEventAccess().getIsCaseSensitiveIsCaseSensitiveKeyword_2_0()); }
		(
			{ before(grammarAccess.getTypeRacerEventAccess().getIsCaseSensitiveIsCaseSensitiveKeyword_2_0()); }
			'isCaseSensitive'
			{ after(grammarAccess.getTypeRacerEventAccess().getIsCaseSensitiveIsCaseSensitiveKeyword_2_0()); }
		)
		{ after(grammarAccess.getTypeRacerEventAccess().getIsCaseSensitiveIsCaseSensitiveKeyword_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__DifficultyAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTypeRacerEventAccess().getDifficultyDifficultyEnumRuleCall_4_0()); }
		ruleDifficulty
		{ after(grammarAccess.getTypeRacerEventAccess().getDifficultyDifficultyEnumRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__TimeLimitAssignment_5_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTypeRacerEventAccess().getTimeLimitEDoubleObjectParserRuleCall_5_1_0()); }
		ruleEDoubleObject
		{ after(grammarAccess.getTypeRacerEventAccess().getTimeLimitEDoubleObjectParserRuleCall_5_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__RetriesAssignment_7
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTypeRacerEventAccess().getRetriesEIntParserRuleCall_7_0()); }
		ruleEInt
		{ after(grammarAccess.getTypeRacerEventAccess().getRetriesEIntParserRuleCall_7_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__SentenceAssignment_9
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTypeRacerEventAccess().getSentenceEStringParserRuleCall_9_0()); }
		ruleEString
		{ after(grammarAccess.getTypeRacerEventAccess().getSentenceEStringParserRuleCall_9_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__TypeRacerEvent__ResultAssignment_11
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTypeRacerEventAccess().getResultEventResultParserRuleCall_11_0()); }
		ruleEventResult
		{ after(grammarAccess.getTypeRacerEventAccess().getResultEventResultParserRuleCall_11_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__DifficultyAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionEventAccess().getDifficultyDifficultyEnumRuleCall_3_0()); }
		ruleDifficulty
		{ after(grammarAccess.getQuestionEventAccess().getDifficultyDifficultyEnumRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__TimeLimitAssignment_4_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionEventAccess().getTimeLimitEDoubleObjectParserRuleCall_4_1_0()); }
		ruleEDoubleObject
		{ after(grammarAccess.getQuestionEventAccess().getTimeLimitEDoubleObjectParserRuleCall_4_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__RetriesAssignment_6
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionEventAccess().getRetriesEIntParserRuleCall_6_0()); }
		ruleEInt
		{ after(grammarAccess.getQuestionEventAccess().getRetriesEIntParserRuleCall_6_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__QuestionAssignment_8
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionEventAccess().getQuestionEStringParserRuleCall_8_0()); }
		ruleEString
		{ after(grammarAccess.getQuestionEventAccess().getQuestionEStringParserRuleCall_8_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__ResultAssignment_10
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionEventAccess().getResultEventResultParserRuleCall_10_0()); }
		ruleEventResult
		{ after(grammarAccess.getQuestionEventAccess().getResultEventResultParserRuleCall_10_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__OptionsAssignment_13
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionEventAccess().getOptionsOptionParserRuleCall_13_0()); }
		ruleOption
		{ after(grammarAccess.getQuestionEventAccess().getOptionsOptionParserRuleCall_13_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__QuestionEvent__OptionsAssignment_14_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getQuestionEventAccess().getOptionsOptionParserRuleCall_14_1_0()); }
		ruleOption
		{ after(grammarAccess.getQuestionEventAccess().getOptionsOptionParserRuleCall_14_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Option__TextAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getOptionAccess().getTextEStringParserRuleCall_2_0()); }
		ruleEString
		{ after(grammarAccess.getOptionAccess().getTextEStringParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Option__IsCorrectAnswerAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getOptionAccess().getIsCorrectAnswerIsCorrectAnswerKeyword_3_0()); }
		(
			{ before(grammarAccess.getOptionAccess().getIsCorrectAnswerIsCorrectAnswerKeyword_3_0()); }
			'isCorrectAnswer'
			{ after(grammarAccess.getOptionAccess().getIsCorrectAnswerIsCorrectAnswerKeyword_3_0()); }
		)
		{ after(grammarAccess.getOptionAccess().getIsCorrectAnswerIsCorrectAnswerKeyword_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
