/*
 * generated by Xtext 2.40.0
 */
package no.ntnu.tdt4250.rf.serializer;

import com.google.inject.Inject;
import java.util.Set;
import no.ntnu.tdt4250.rf.EventPack;
import no.ntnu.tdt4250.rf.EventResult;
import no.ntnu.tdt4250.rf.Option;
import no.ntnu.tdt4250.rf.QuestionEvent;
import no.ntnu.tdt4250.rf.RfPackage;
import no.ntnu.tdt4250.rf.TypeRacerEvent;
import no.ntnu.tdt4250.rf.services.RealmForgeDslGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;

@SuppressWarnings("all")
public class RealmForgeDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private RealmForgeDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == RfPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case RfPackage.EVENT_PACK:
				sequence_EventPack(context, (EventPack) semanticObject); 
				return; 
			case RfPackage.EVENT_RESULT:
				sequence_EventResult(context, (EventResult) semanticObject); 
				return; 
			case RfPackage.OPTION:
				sequence_Option(context, (Option) semanticObject); 
				return; 
			case RfPackage.QUESTION_EVENT:
				sequence_QuestionEvent(context, (QuestionEvent) semanticObject); 
				return; 
			case RfPackage.TYPE_RACER_EVENT:
				sequence_TypeRacerEvent(context, (TypeRacerEvent) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     EventPack returns EventPack
	 *
	 * Constraint:
	 *     (name=EString description=EString unit=EString events+=Event*)
	 * </pre>
	 */
	protected void sequence_EventPack(ISerializationContext context, EventPack semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     EventResult returns EventResult
	 *
	 * Constraint:
	 *     message=EString?
	 * </pre>
	 */
	protected void sequence_EventResult(ISerializationContext context, EventResult semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Option returns Option
	 *
	 * Constraint:
	 *     (text=EString isCorrectAnswer?='isCorrectAnswer'?)
	 * </pre>
	 */
	protected void sequence_Option(ISerializationContext context, Option semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Event returns QuestionEvent
	 *     QuestionEvent returns QuestionEvent
	 *
	 * Constraint:
	 *     (
	 *         difficulty=Difficulty 
	 *         timeLimit=EDoubleObject? 
	 *         retries=EInt 
	 *         question=EString 
	 *         result=EventResult 
	 *         options+=Option 
	 *         options+=Option*
	 *     )
	 * </pre>
	 */
	protected void sequence_QuestionEvent(ISerializationContext context, QuestionEvent semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Event returns TypeRacerEvent
	 *     TypeRacerEvent returns TypeRacerEvent
	 *
	 * Constraint:
	 *     (
	 *         isCaseSensitive?='isCaseSensitive'? 
	 *         difficulty=Difficulty 
	 *         timeLimit=EDoubleObject? 
	 *         retries=EInt 
	 *         sentence=EString 
	 *         result=EventResult
	 *     )
	 * </pre>
	 */
	protected void sequence_TypeRacerEvent(ISerializationContext context, TypeRacerEvent semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
