/*
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.rf.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class RealmForgeDslProposalProvider extends AbstractRealmForgeDslProposalProvider {
}
