addGoal.title=null
addGoal.goalType=null
addGoal.value=null
addGoal.addButton=null
addGoal.warning=null
addGoal.warningMessage=null
addGoal.cancelButton=null
addGoal.conformation=null
addGoal.conformationMessage=null
addGoal.goalTypePlaceholder=null
addGoal.goldGoal=null
addGoal.healthGoal=null
addGoal.inventoryGoal=null
addGoal.scoreGoal=null
addGoal.lettersPlaceholder=null
addGoal.numbersPlaceholder=null
