/*
 * generated by Xtext 2.40.0
 */
package no.ntnu.tdt4250.rf.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RealmForgeDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("no/ntnu/tdt4250/rf/parser/antlr/internal/InternalRealmForgeDsl.tokens");
	}
}
