/*
 * generated by Xtext 2.40.0
 */
package no.ntnu.tdt4250.rf.parser.antlr;

import com.google.inject.Inject;
import no.ntnu.tdt4250.rf.parser.antlr.internal.InternalRealmForgeDslParser;
import no.ntnu.tdt4250.rf.services.RealmForgeDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RealmForgeDslParser extends AbstractAntlrParser {

	@Inject
	private RealmForgeDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRealmForgeDslParser createParser(XtextTokenStream stream) {
		return new InternalRealmForgeDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "EventPack";
	}

	public RealmForgeDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RealmForgeDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
