/*
 * generated by Xtext 2.40.0
 */
package no.ntnu.tdt4250.rf.ui;

import com.google.inject.Injector;
import no.ntnu.tdt4250.rfdsl.ui.internal.RfdslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RealmForgeDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(RfdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		RfdslActivator activator = RfdslActivator.getInstance();
		return activator != null ? activator.getInjector(RfdslActivator.NO_NTNU_TDT4250_RF_REALMFORGEDSL) : null;
	}

}
