/*
 * generated by Xtext 2.40.0
 */
grammar InternalRealmForgeDsl;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package no.ntnu.tdt4250.rf.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package no.ntnu.tdt4250.rf.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import no.ntnu.tdt4250.rf.services.RealmForgeDslGrammarAccess;

}

@parser::members {

 	private RealmForgeDslGrammarAccess grammarAccess;

    public InternalRealmForgeDslParser(TokenStream input, RealmForgeDslGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "EventPack";
   	}

   	@Override
   	protected RealmForgeDslGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleEventPack
entryRuleEventPack returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getEventPackRule()); }
	iv_ruleEventPack=ruleEventPack
	{ $current=$iv_ruleEventPack.current; }
	EOF;

// Rule EventPack
ruleEventPack returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='name'
		{
			newLeafNode(otherlv_0, grammarAccess.getEventPackAccess().getNameKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getEventPackAccess().getNameEStringParserRuleCall_1_0());
				}
				lv_name_1_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getEventPackRule());
					}
					set(
						$current,
						"name",
						lv_name_1_0,
						"no.ntnu.tdt4250.rf.RealmForgeDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2='description'
		{
			newLeafNode(otherlv_2, grammarAccess.getEventPackAccess().getDescriptionKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getEventPackAccess().getDescriptionEStringParserRuleCall_3_0());
				}
				lv_description_3_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getEventPackRule());
					}
					set(
						$current,
						"description",
						lv_description_3_0,
						"no.ntnu.tdt4250.rf.RealmForgeDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='unit'
		{
			newLeafNode(otherlv_4, grammarAccess.getEventPackAccess().getUnitKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getEventPackAccess().getUnitEStringParserRuleCall_5_0());
				}
				lv_unit_5_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getEventPackRule());
					}
					set(
						$current,
						"unit",
						lv_unit_5_0,
						"no.ntnu.tdt4250.rf.RealmForgeDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getEventPackAccess().getEventsEventParserRuleCall_6_0());
				}
				lv_events_6_0=ruleEvent
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getEventPackRule());
					}
					add(
						$current,
						"events",
						lv_events_6_0,
						"no.ntnu.tdt4250.rf.RealmForgeDsl.Event");
					afterParserOrEnumRuleCall();
				}
			)
		)*
	)
;

// Entry rule entryRuleEvent
entryRuleEvent returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getEventRule()); }
	iv_ruleEvent=ruleEvent
	{ $current=$iv_ruleEvent.current; }
	EOF;

// Rule Event
ruleEvent returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getEventAccess().getTypeRacerEventParserRuleCall_0());
		}
		this_TypeRacerEvent_0=ruleTypeRacerEvent
		{
			$current = $this_TypeRacerEvent_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getEventAccess().getQuestionEventParserRuleCall_1());
		}
		this_QuestionEvent_1=ruleQuestionEvent
		{
			$current = $this_QuestionEvent_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleEString
entryRuleEString returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEStringRule()); }
	iv_ruleEString=ruleEString
	{ $current=$iv_ruleEString.current.getText(); }
	EOF;

// Rule EString
ruleEString returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_STRING_0=RULE_STRING
		{
			$current.merge(this_STRING_0);
		}
		{
			newLeafNode(this_STRING_0, grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0());
		}
		    |
		this_ID_1=RULE_ID
		{
			$current.merge(this_ID_1);
		}
		{
			newLeafNode(this_ID_1, grammarAccess.getEStringAccess().getIDTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleEDoubleObject
entryRuleEDoubleObject returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEDoubleObjectRule()); }
	iv_ruleEDoubleObject=ruleEDoubleObject
	{ $current=$iv_ruleEDoubleObject.current.getText(); }
	EOF;

// Rule EDoubleObject
ruleEDoubleObject returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			kw='-'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getEDoubleObjectAccess().getHyphenMinusKeyword_0());
			}
		)?
		(
			this_INT_1=RULE_INT
			{
				$current.merge(this_INT_1);
			}
			{
				newLeafNode(this_INT_1, grammarAccess.getEDoubleObjectAccess().getINTTerminalRuleCall_1());
			}
		)?
		kw='.'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEDoubleObjectAccess().getFullStopKeyword_2());
		}
		this_INT_3=RULE_INT
		{
			$current.merge(this_INT_3);
		}
		{
			newLeafNode(this_INT_3, grammarAccess.getEDoubleObjectAccess().getINTTerminalRuleCall_3());
		}
		(
			(
				kw='E'
				{
					$current.merge(kw);
					newLeafNode(kw, grammarAccess.getEDoubleObjectAccess().getEKeyword_4_0_0());
				}
				    |
				kw='e'
				{
					$current.merge(kw);
					newLeafNode(kw, grammarAccess.getEDoubleObjectAccess().getEKeyword_4_0_1());
				}
			)
			(
				kw='-'
				{
					$current.merge(kw);
					newLeafNode(kw, grammarAccess.getEDoubleObjectAccess().getHyphenMinusKeyword_4_1());
				}
			)?
			this_INT_7=RULE_INT
			{
				$current.merge(this_INT_7);
			}
			{
				newLeafNode(this_INT_7, grammarAccess.getEDoubleObjectAccess().getINTTerminalRuleCall_4_2());
			}
		)?
	)
;

// Entry rule entryRuleEInt
entryRuleEInt returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEIntRule()); }
	iv_ruleEInt=ruleEInt
	{ $current=$iv_ruleEInt.current.getText(); }
	EOF;

// Rule EInt
ruleEInt returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			kw='-'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getEIntAccess().getHyphenMinusKeyword_0());
			}
		)?
		this_INT_1=RULE_INT
		{
			$current.merge(this_INT_1);
		}
		{
			newLeafNode(this_INT_1, grammarAccess.getEIntAccess().getINTTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleEventResult
entryRuleEventResult returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getEventResultRule()); }
	iv_ruleEventResult=ruleEventResult
	{ $current=$iv_ruleEventResult.current; }
	EOF;

// Rule EventResult
ruleEventResult returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getEventResultAccess().getEventResultAction_0(),
					$current);
			}
		)
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getEventResultAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			otherlv_2='message'
			{
				newLeafNode(otherlv_2, grammarAccess.getEventResultAccess().getMessageKeyword_2_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getEventResultAccess().getMessageEStringParserRuleCall_2_1_0());
					}
					lv_message_3_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getEventResultRule());
						}
						set(
							$current,
							"message",
							lv_message_3_0,
							"no.ntnu.tdt4250.rf.RealmForgeDsl.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_4='}'
		{
			newLeafNode(otherlv_4, grammarAccess.getEventResultAccess().getRightCurlyBracketKeyword_3());
		}
	)
;

// Entry rule entryRuleTypeRacerEvent
entryRuleTypeRacerEvent returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTypeRacerEventRule()); }
	iv_ruleTypeRacerEvent=ruleTypeRacerEvent
	{ $current=$iv_ruleTypeRacerEvent.current; }
	EOF;

// Rule TypeRacerEvent
ruleTypeRacerEvent returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='TypeRacerEvent'
		{
			newLeafNode(otherlv_0, grammarAccess.getTypeRacerEventAccess().getTypeRacerEventKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getTypeRacerEventAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			(
				lv_isCaseSensitive_2_0='isCaseSensitive'
				{
					newLeafNode(lv_isCaseSensitive_2_0, grammarAccess.getTypeRacerEventAccess().getIsCaseSensitiveIsCaseSensitiveKeyword_2_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTypeRacerEventRule());
					}
					setWithLastConsumed($current, "isCaseSensitive", lv_isCaseSensitive_2_0 != null, "isCaseSensitive");
				}
			)
		)?
		otherlv_3='difficulty'
		{
			newLeafNode(otherlv_3, grammarAccess.getTypeRacerEventAccess().getDifficultyKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTypeRacerEventAccess().getDifficultyDifficultyEnumRuleCall_4_0());
				}
				lv_difficulty_4_0=ruleDifficulty
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTypeRacerEventRule());
					}
					set(
						$current,
						"difficulty",
						lv_difficulty_4_0,
						"no.ntnu.tdt4250.rf.RealmForgeDsl.Difficulty");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_5='timeLimit'
			{
				newLeafNode(otherlv_5, grammarAccess.getTypeRacerEventAccess().getTimeLimitKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getTypeRacerEventAccess().getTimeLimitEDoubleObjectParserRuleCall_5_1_0());
					}
					lv_timeLimit_6_0=ruleEDoubleObject
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getTypeRacerEventRule());
						}
						set(
							$current,
							"timeLimit",
							lv_timeLimit_6_0,
							"no.ntnu.tdt4250.rf.RealmForgeDsl.EDoubleObject");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_7='retries'
		{
			newLeafNode(otherlv_7, grammarAccess.getTypeRacerEventAccess().getRetriesKeyword_6());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTypeRacerEventAccess().getRetriesEIntParserRuleCall_7_0());
				}
				lv_retries_8_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTypeRacerEventRule());
					}
					set(
						$current,
						"retries",
						lv_retries_8_0,
						"no.ntnu.tdt4250.rf.RealmForgeDsl.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_9='sentence'
		{
			newLeafNode(otherlv_9, grammarAccess.getTypeRacerEventAccess().getSentenceKeyword_8());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTypeRacerEventAccess().getSentenceEStringParserRuleCall_9_0());
				}
				lv_sentence_10_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTypeRacerEventRule());
					}
					set(
						$current,
						"sentence",
						lv_sentence_10_0,
						"no.ntnu.tdt4250.rf.RealmForgeDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_11='result'
		{
			newLeafNode(otherlv_11, grammarAccess.getTypeRacerEventAccess().getResultKeyword_10());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTypeRacerEventAccess().getResultEventResultParserRuleCall_11_0());
				}
				lv_result_12_0=ruleEventResult
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTypeRacerEventRule());
					}
					set(
						$current,
						"result",
						lv_result_12_0,
						"no.ntnu.tdt4250.rf.RealmForgeDsl.EventResult");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_13='}'
		{
			newLeafNode(otherlv_13, grammarAccess.getTypeRacerEventAccess().getRightCurlyBracketKeyword_12());
		}
	)
;

// Entry rule entryRuleQuestionEvent
entryRuleQuestionEvent returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getQuestionEventRule()); }
	iv_ruleQuestionEvent=ruleQuestionEvent
	{ $current=$iv_ruleQuestionEvent.current; }
	EOF;

// Rule QuestionEvent
ruleQuestionEvent returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='QuestionEvent'
		{
			newLeafNode(otherlv_0, grammarAccess.getQuestionEventAccess().getQuestionEventKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getQuestionEventAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='difficulty'
		{
			newLeafNode(otherlv_2, grammarAccess.getQuestionEventAccess().getDifficultyKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getQuestionEventAccess().getDifficultyDifficultyEnumRuleCall_3_0());
				}
				lv_difficulty_3_0=ruleDifficulty
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getQuestionEventRule());
					}
					set(
						$current,
						"difficulty",
						lv_difficulty_3_0,
						"no.ntnu.tdt4250.rf.RealmForgeDsl.Difficulty");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_4='timeLimit'
			{
				newLeafNode(otherlv_4, grammarAccess.getQuestionEventAccess().getTimeLimitKeyword_4_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getQuestionEventAccess().getTimeLimitEDoubleObjectParserRuleCall_4_1_0());
					}
					lv_timeLimit_5_0=ruleEDoubleObject
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getQuestionEventRule());
						}
						set(
							$current,
							"timeLimit",
							lv_timeLimit_5_0,
							"no.ntnu.tdt4250.rf.RealmForgeDsl.EDoubleObject");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_6='retries'
		{
			newLeafNode(otherlv_6, grammarAccess.getQuestionEventAccess().getRetriesKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getQuestionEventAccess().getRetriesEIntParserRuleCall_6_0());
				}
				lv_retries_7_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getQuestionEventRule());
					}
					set(
						$current,
						"retries",
						lv_retries_7_0,
						"no.ntnu.tdt4250.rf.RealmForgeDsl.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_8='question'
		{
			newLeafNode(otherlv_8, grammarAccess.getQuestionEventAccess().getQuestionKeyword_7());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getQuestionEventAccess().getQuestionEStringParserRuleCall_8_0());
				}
				lv_question_9_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getQuestionEventRule());
					}
					set(
						$current,
						"question",
						lv_question_9_0,
						"no.ntnu.tdt4250.rf.RealmForgeDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_10='result'
		{
			newLeafNode(otherlv_10, grammarAccess.getQuestionEventAccess().getResultKeyword_9());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getQuestionEventAccess().getResultEventResultParserRuleCall_10_0());
				}
				lv_result_11_0=ruleEventResult
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getQuestionEventRule());
					}
					set(
						$current,
						"result",
						lv_result_11_0,
						"no.ntnu.tdt4250.rf.RealmForgeDsl.EventResult");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_12='options'
		{
			newLeafNode(otherlv_12, grammarAccess.getQuestionEventAccess().getOptionsKeyword_11());
		}
		otherlv_13='{'
		{
			newLeafNode(otherlv_13, grammarAccess.getQuestionEventAccess().getLeftCurlyBracketKeyword_12());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getQuestionEventAccess().getOptionsOptionParserRuleCall_13_0());
				}
				lv_options_14_0=ruleOption
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getQuestionEventRule());
					}
					add(
						$current,
						"options",
						lv_options_14_0,
						"no.ntnu.tdt4250.rf.RealmForgeDsl.Option");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_15=','
			{
				newLeafNode(otherlv_15, grammarAccess.getQuestionEventAccess().getCommaKeyword_14_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getQuestionEventAccess().getOptionsOptionParserRuleCall_14_1_0());
					}
					lv_options_16_0=ruleOption
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getQuestionEventRule());
						}
						add(
							$current,
							"options",
							lv_options_16_0,
							"no.ntnu.tdt4250.rf.RealmForgeDsl.Option");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_17='}'
		{
			newLeafNode(otherlv_17, grammarAccess.getQuestionEventAccess().getRightCurlyBracketKeyword_15());
		}
		otherlv_18='}'
		{
			newLeafNode(otherlv_18, grammarAccess.getQuestionEventAccess().getRightCurlyBracketKeyword_16());
		}
	)
;

// Entry rule entryRuleOption
entryRuleOption returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getOptionRule()); }
	iv_ruleOption=ruleOption
	{ $current=$iv_ruleOption.current; }
	EOF;

// Rule Option
ruleOption returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='{'
		{
			newLeafNode(otherlv_0, grammarAccess.getOptionAccess().getLeftCurlyBracketKeyword_0());
		}
		otherlv_1='text'
		{
			newLeafNode(otherlv_1, grammarAccess.getOptionAccess().getTextKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getOptionAccess().getTextEStringParserRuleCall_2_0());
				}
				lv_text_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getOptionRule());
					}
					set(
						$current,
						"text",
						lv_text_2_0,
						"no.ntnu.tdt4250.rf.RealmForgeDsl.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				lv_isCorrectAnswer_3_0='isCorrectAnswer'
				{
					newLeafNode(lv_isCorrectAnswer_3_0, grammarAccess.getOptionAccess().getIsCorrectAnswerIsCorrectAnswerKeyword_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getOptionRule());
					}
					setWithLastConsumed($current, "isCorrectAnswer", lv_isCorrectAnswer_3_0 != null, "isCorrectAnswer");
				}
			)
		)?
		otherlv_4='}'
		{
			newLeafNode(otherlv_4, grammarAccess.getOptionAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Rule Difficulty
ruleDifficulty returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='EASY'
			{
				$current = grammarAccess.getDifficultyAccess().getEASYEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getDifficultyAccess().getEASYEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='NORMAL'
			{
				$current = grammarAccess.getDifficultyAccess().getNORMALEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getDifficultyAccess().getNORMALEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='HARD'
			{
				$current = grammarAccess.getDifficultyAccess().getHARDEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getDifficultyAccess().getHARDEnumLiteralDeclaration_2());
			}
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
