/*
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.rf.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import no.ntnu.tdt4250.rf.RealmForgeDslRuntimeModule;
import no.ntnu.tdt4250.rf.RealmForgeDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RealmForgeDslIdeSetup extends RealmForgeDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RealmForgeDslRuntimeModule(), new RealmForgeDslIdeModule()));
	}
	
}
