/*
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.rf.ide;


/**
 * Use this class to register ide components.
 */
public class RealmForgeDslIdeModule extends AbstractRealmForgeDslIdeModule {
}
