package no.ntnu.tdt4250.rf.genjava;

import java.util.Set;
import no.ntnu.tdt4250.rf.Difficulty;
import no.ntnu.tdt4250.rf.Event;
import no.ntnu.tdt4250.rf.EventPack;
import no.ntnu.tdt4250.rf.QuestionEvent;
import no.ntnu.tdt4250.rf.TypeRacerEvent;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;

@SuppressWarnings("all")
public class EventPackCssGenerator {
  private final EventPack ep;

  public EventPackCssGenerator(final EventPack ep) {
    this.ep = ep;
  }

  public CharSequence generate() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/* ============================================================");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("Auto-generated CSS for ");
    String _name = this.ep.getName();
    _builder.append(_name, "   ");
    _builder.newLineIfNotEmpty();
    _builder.append("   ");
    _builder.append("Styles for Event View (EventController + event.fxml)");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("============================================================ */");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* ------------------------------------------------------------");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("Root layout (BorderPane with styleClass=\"mini-root\")");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("------------------------------------------------------------ */");
    _builder.newLine();
    _builder.append(".mini-root {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-color: #121212;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-font-family: \"Segoe UI\", sans-serif;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-text-fill: #f0f0f0;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* ------------------------------------------------------------");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("Card container (StackPane with styleClass=\"card-root\")");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("------------------------------------------------------------ */");
    _builder.newLine();
    _builder.append(".card-root {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-color: #1e1e1e;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-radius: 16;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-padding: 0;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-effect: dropshadow(gaussian, black, 20, 0.2, 0, 6);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* ============================================================");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("TEXT STYLES");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("============================================================ */");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* Event title */");
    _builder.newLine();
    _builder.append(".header-label {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-font-size: 24px;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-font-weight: bold;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-text-fill: #ffffff;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* Small informational text (event type, difficulty, etc.) */");
    _builder.newLine();
    _builder.append(".info-label {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-font-size: 14px;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-text-fill: #b0bec5;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* Question/title inside card */");
    _builder.newLine();
    _builder.append(".question-label {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-font-size: 18px;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-text-fill: #f5f5f5;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* Feedback text below input/options */");
    _builder.newLine();
    _builder.append(".feedback-label {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-font-size: 14px;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-text-fill: #e0e0e0;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* Result message after answering */");
    _builder.newLine();
    _builder.append(".result-label {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-font-size: 16px;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-font-weight: bold;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-text-fill: #ffffff;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* Rewards (units earned) */");
    _builder.newLine();
    _builder.append(".rewards-label {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-font-size: 14px;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-text-fill: #ffd54f;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* Timer text in the top bar */");
    _builder.newLine();
    _builder.append(".timer-label {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-font-size: 16px;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-text-fill: #ffffff;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* ============================================================");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("TIMER PROGRESS BAR");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("============================================================ */");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".timer-bar {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-accent: #42a5f5;              /* fill colour */");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-control-inner-background: #2a2a2a;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-radius: 8;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-border-radius: 8;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* ============================================================");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("INPUT FIELD");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("============================================================ */");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".answer-field {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-radius: 8;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-padding: 8 10;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-color: #2a2a2a;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-text-fill: white;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-border-color: #444;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-border-radius: 8;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".answer-field:focused {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-border-color: #64b5f6;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* ============================================================");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("GLOBAL BUTTON STYLES");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("============================================================ */");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".primary-button {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-padding: 10 18;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-radius: 8;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-color: #42a5f5;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-text-fill: white;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-font-weight: bold;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-cursor: hand;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".primary-button:hover {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-color: #64b5f6;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".secondary-button {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-padding: 10 18;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-radius: 8;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-color: #2c2c2c;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-text-fill: #eeeeee;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-cursor: hand;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".secondary-button:hover {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-color: #3a3a3a;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* ============================================================");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("OPTION BUTTONS (created at runtime in EventController)");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("============================================================ */");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".option-button {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-padding: 10 14;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-radius: 8;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-color: #263238;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-text-fill: #eceff1;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-font-size: 14px;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-alignment: CENTER_LEFT;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".option-button:hover {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-color: #37474f;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* Used together with option-button in your controller */");
    _builder.newLine();
    _builder.append(".selectable-option {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("/* can be used for generic selectable styling if needed */");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* Toggled state in controller.toggleOption(...) */");
    _builder.newLine();
    _builder.append(".selected-option {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-background-color: #1e88e5;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-text-fill: white;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-border-color: #90caf9;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-border-width: 2;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("-fx-border-radius: 8;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* ============================================================");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("DYNAMIC STYLING BASED ON DSL MODEL");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("These classes are intended to be added at runtime from");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("EventController or EventHandler to the root node:");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("- difficulty-* (easy, normal, hard)");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("- event-type-question / event-type-typeracer");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("- timed-event");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("============================================================ */");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/* -----------------------------");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("DIFFICULTY-BASED CARD BORDERS");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("----------------------------- */");
    _builder.newLine();
    {
      final Function1<Event, Difficulty> _function = (Event it) -> {
        return it.getDifficulty();
      };
      Set<Difficulty> _set = IterableExtensions.<Difficulty>toSet(ListExtensions.<Event, Difficulty>map(this.ep.getEvents(), _function));
      for(final Difficulty d : _set) {
        _builder.append(".difficulty-");
        String _lowerCase = d.getName().toLowerCase();
        _builder.append(_lowerCase);
        _builder.append(" .card-root {");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("-fx-border-color: ");
        String _colorForDifficulty = this.colorForDifficulty(d);
        _builder.append(_colorForDifficulty, "    ");
        _builder.append(";");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("-fx-border-width: 2;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("-fx-border-radius: 16;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
      }
    }
    _builder.newLine();
    _builder.append("/* -----------------------------");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("EVENT TYPE TINTING");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("----------------------------- */");
    _builder.newLine();
    {
      final Function1<Event, Boolean> _function_1 = (Event it) -> {
        return Boolean.valueOf((it instanceof QuestionEvent));
      };
      boolean _exists = IterableExtensions.<Event>exists(this.ep.getEvents(), _function_1);
      if (_exists) {
        _builder.append("/* Question events get a bluish tint */");
        _builder.newLine();
        _builder.append(".event-type-question .card-root {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("-fx-background-color: #18222e;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
      }
    }
    _builder.newLine();
    {
      final Function1<Event, Boolean> _function_2 = (Event it) -> {
        return Boolean.valueOf((it instanceof TypeRacerEvent));
      };
      boolean _exists_1 = IterableExtensions.<Event>exists(this.ep.getEvents(), _function_2);
      if (_exists_1) {
        _builder.append("/* TypeRacer events get a reddish tint */");
        _builder.newLine();
        _builder.append(".event-type-typeracer .card-root {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("-fx-background-color: #26181e;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
      }
    }
    _builder.newLine();
    _builder.append("/* -----------------------------");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("TIMED EVENTS");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("----------------------------- */");
    _builder.newLine();
    {
      final Function1<Event, Boolean> _function_3 = (Event it) -> {
        return Boolean.valueOf(((it.getTimeLimit() != null) && ((it.getTimeLimit()).doubleValue() > 0.0)));
      };
      boolean _exists_2 = IterableExtensions.<Event>exists(this.ep.getEvents(), _function_3);
      if (_exists_2) {
        _builder.append(".timed-event .timer-label {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("-fx-text-fill: #ffeb3b;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("-fx-font-weight: bold;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
      }
    }
    return _builder;
  }

  private String colorForDifficulty(final Difficulty d) {
    String _switchResult = null;
    if (d != null) {
      switch (d) {
        case EASY:
          _switchResult = "#4caf50";
          break;
        case NORMAL:
          _switchResult = "#ff9800";
          break;
        case HARD:
          _switchResult = "#f44336";
          break;
        default:
          _switchResult = "#9e9e9e";
          break;
      }
    } else {
      _switchResult = "#9e9e9e";
    }
    return _switchResult;
  }
}
