/*
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.rf;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RealmForgeDslRuntimeModule extends AbstractRealmForgeDslRuntimeModule {
}
