/**
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.rf.generator;

import no.ntnu.tdt4250.rf.EventPack;
import no.ntnu.tdt4250.rf.genjava.EventPackCssGenerator;
import no.ntnu.tdt4250.rf.genjava.EventPackGameHandlerGenerator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IterableExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class RealmForgeDslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IterableExtensions.<EObject>head(resource.getContents());
    final EventPack eventPack = ((EventPack) _head);
    final EventPackGameHandlerGenerator eventPackHandlerGenerator = new EventPackGameHandlerGenerator(eventPack);
    fsa.generateFile(
      "EventHandler.java", 
      eventPackHandlerGenerator.generate());
    final EventPackCssGenerator cssGenerator = new EventPackCssGenerator(eventPack);
    fsa.generateFile(
      "css/minigame.css", 
      cssGenerator.generate());
  }
}
