/*
 * generated by Xtext 2.40.0
 */
package no.ntnu.tdt4250.rf.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRealmForgeDslScopeProvider extends DelegatingScopeProvider {
}
