#

pluginName = no.ntnu.tdt4250.rf Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Trigger_type = Trigger
_UI_EventPack_type = Event Pack
_UI_Event_type = Event
_UI_TypeRacerEvent_type = Type Racer Event
_UI_QuizEvent_type = Quiz Event
_UI_MathEvent_type = Math Event
_UI_EventSettings_type = Event Settings
_UI_QuestionEvent_type = Question Event
_UI_Option_type = Option
_UI_EventResult_type = Event Result
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Trigger_condition_feature = Condition
_UI_EventPack_event_feature = Event
_UI_EventPack_name_feature = Name
_UI_EventPack_trigger_feature = Trigger
_UI_EventPack_description_feature = Description
_UI_Event_difficulty_feature = Difficulty
_UI_Event_reusable_feature = Reusable
_UI_Event_timeLimit_feature = Time Limit
_UI_Event_retries_feature = Retries
_UI_TypeRacerEvent_sentence_feature = Sentence
_UI_TypeRacerEvent_isCaseSensitive_feature = Is Case Sensitive
_UI_TypeRacerEvent_timeToTypeSentence_feature = Time To Type Sentence
_UI_EventSettings_timeLimit_feature = Time Limit
_UI_EventSettings_retries_feature = Retries
_UI_QuestionEvent_question_feature = Question
_UI_QuestionEvent_options_feature = Options
_UI_QuestionEvent_multipleChoice_feature = Multiple Choice
_UI_QuestionEvent_multipleCorrectAnswers_feature = Multiple Correct Answers
_UI_Option_text_feature = Text
_UI_Option_isCorrectAnswer_feature = Is Correct Answer
_UI_EventResult_message_feature = Message
_UI_EventResult_event_feature = Event
_UI_EventResult_goldEarned_feature = Gold Earned
_UI_Unknown_feature = Unspecified

_UI_Difficulty_EASY_literal = EASY
_UI_Difficulty_NORMAL_literal = NORMAL
_UI_Difficulty_HARD_literal = HARD
_UI_EventPack_events_feature = Events
_UI_Event_results_feature = Results
_UI_EventPack_unit_feature = Unit
_UI_EventResult_unitsEarnedMessage_feature = Units Earned Message
_UI_Event_result_feature = Result
_UI_Event_eventpack_feature = Eventpack
