/*
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.rf.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import no.ntnu.tdt4250.rf.EventPack
import no.ntnu.tdt4250.rf.genjava.EventPackGameHandlerGenerator
import no.ntnu.tdt4250.rf.genjava.EventPackCssGenerator

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class RealmForgeDslGenerator extends AbstractGenerator {

	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		val eventPack = resource.contents.head as EventPack
		
		val eventPackHandlerGenerator = new EventPackGameHandlerGenerator(eventPack)
		
		// EventHandler generator
		fsa.generateFile(
			'EventHandler.java',
			eventPackHandlerGenerator.generate()
		)
		
		// CSS generator
        val cssGenerator = new EventPackCssGenerator(eventPack)
        fsa.generateFile(
            'css/minigame.css', 
            cssGenerator.generate()
        )
	}
}