{
  "name": "portfolio",
  "version": "2.0.8",
  "homepage": "https://danielhoyland.github.io/Portfolio/",
  "description": "Here is my repo for all projects I have done in school, as hobby or other",
  "main": "portfolio.jsx",
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "predeploy": "npm run build",
    "deploy": "gh-pages -d build"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bootstrap": "^5.3.7",
    "framer-motion": "^12.17.3",
    "lucide-react": "^0.522.0",
    "react": "^19.1.0",
    "react-bootstrap": "^2.10.10",
    "react-dom": "^19.1.0",
    "react-responsive-carousel": "^3.2.23",
    "react-slick": "^0.30.3",
    "slick-carousel": "^1.8.1",
    "react-scripts": "5.0.1"
  },
  "devDependencies": {
    "gh-pages": "^6.3.0"
  }
}
